### ISSUE TITLE
Cambiare Host e port

### ISSUE THREAD

**Issue by Claudio97Mariuzzo** [LulaSan/GreenHouse#1]
https://github.com/LulaSan/GreenHouse/blob/199146e294342f0b92601615f8c239d59b7fa6e1/Sensors_%26_Controllers/Green_Brgth.py#L25

Ricordarsi di prendere host e port da un file setting.json relativo ai sensori, nei quali indichi host e port
Vedi file setting nella cartella post process

**Comment by Claudio97Mariuzzo** [comment]
Cosi come per tutti gli altri sensori

**Comment by gregoriobattaglia** [comment]
did it!
