### ISSUE TITLE
Telegram utils.json

### ISSUE THREAD

**Issue by Claudio97Mariuzzo** [LulaSan/GreenHouse#3]
Luisa postresti aggiungere al file le mie credenziali sotto forma di admin A in modo da testare tutte le funzionalità? altrimenti ho solo accesso al farmer. Io non posso modificarlo perchè il tuo file è sul server e sta runnando, quindi se provo io va in conflitto

**Comment by LulaSan** [comment]
Puoi utilizzare quelle già presenti nel catalog, tipo questa "ADMIN_ID":"12345"...
```

 "Admins": [
        {
            "ADMIN_ID":"12345"
        },
        {
            "ADMIN_ID":"56789"
        }
```
