### ISSUE TITLE
Catalog_Update

### ISSUE THREAD

**Issue by gregoriobattaglia** [LulaSan/GreenHouse#4]
DOVREBBE AVERE VOCI DI QUESTO TIPO CON I TOPIC LEGATI ALL'ID DELLA GREENHOUSE

        {
            "GREENHOUSE_ID": "ABCDEFG",
            "NAME":"Sassari's Greenhouse",
            "GREENHOUSE_LATITUDE": 42.067,
            "GREENHOUSE_LONGITUDE": 8.9,
            "STATUS_CONTROLL_HUMIDITY": 1,
            "STATUS_PUMP":1,
            "THRESHOLD_HUMID_MIN": 20,
            "THRESHOLD_HUMID_MAX": 40,
            "STATUS_CONTROLL_BRIGTH": 1,
            "STATUS_WINDOW":1,
            "THRESHOLD_BRIGHT_MIN": 20,
            "THRESHOLD_BRIGHT_MAX": 50,
            "STATUS_CONTROLL_TEMPER": 1,
            "STATUS_VENT":1,
            "THRESHOLD_TEMPER_MIN": 20,
            "THRESHOLD_TEMPER_MAX": 35,
            "BROKER_HOST": "13.59.136.106",
            "BROKER_PORT": 1883,
            "STATUS_TOPIC": "/p4iot/greenhouses/ABCDEFG/status",
            "COMMANDS_TOPIC": "/p4iot/greenhouses/ABCDEFG/commands/+",
            "SENSORS_TOPIC": "/p4iot/greenhouses/ABCDEFG/sensors"
        }

**Comment by LulaSan** [comment]
Fatto, ho anche rimosso il nome della greenhouse
