### ISSUE TITLE
Temperature e Humidity sui sensori delle piante

### ISSUE THREAD

**Issue by Claudio97Mariuzzo** [LulaSan/GreenHouse#5]
I sensori delle piante Es: ONLINE_Aloe_Hum.py devono mandare sia valore di umidità sia di temperatura
(simulano agrumino che rilevava entrambi)

**Comment by gregoriobattaglia** [comment]
@Claudio97Mariuzzo Risolto!

elimino il vecchio e metto quello che ho fatto

**Comment by gregoriobattaglia** [comment]
Risolto! 

Ti carico intanto quella dell'aloe e sistemo il resto 

è sempre nella cartella ONLINE, il nome è ONLINE_Aloe_Hum_Temp
