### ISSUE TITLE
TOKEN TB

### ISSUE THREAD

**Issue by Claudio97Mariuzzo** [LulaSan/GreenHouse#6]
Ti preparo un foglio con i vari token dei sensori, lo trovi anche nella cartella TB
GREENHOUSE 1:
TEMPERATURA: JWUOpEuPr4xeKahmfrzwv
LUMINOSITà: Wsx4vSU7SCBUPqH4BRN6
UMIDITà: ekxDWtLAM4pk9THRDS3u
GREENHOUSE 2:
TEMPERATURA: JMIPtCmt2I5nW8PIzLHF
LUMINOSITà: Q2SYhCCAM9DQCVSzOakH
UMIDITà: GqJXcA2EtMZfPzs1FvaF
PLANT 1 -PEPERONCINO:
TEMPERATURE/HUMIDITY: svOmnwGu4RlAydXbdMHf
PLANT 2 -ALOE:
TEMPERATURE/HUMIDITY: FgbOm7jGYMFUENoeISR0

**Comment by gregoriobattaglia** [comment]
Perfetto!
